import{o as w}from"./assets/main-CIQFArmN.js";const I="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwY2JkYTQ2NzJkMGZkMWRhYjU3NzJjYjJkNzhhYjMyNCIsIm5iZiI6MTc0MzcxNjUyNC44MjksInN1YiI6IjY3ZWYwMGFjYjNlMDM1Mjg2Y2Q5MWZkMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.j0Mea4sdRcdv4xLRcxt8bZgkEFSrxjdNrJf6CHcoW7k",h="https://api.themoviedb.org/3",B="https://image.tmdb.org/t/p/",k=document.getElementById("search-form-catalog"),m=document.getElementById("search-input-catalog"),c=document.getElementById("clear-search"),v=document.getElementById("movies-grid"),g=document.getElementById("no-results"),l=document.getElementById("pagination");document.getElementById("featured-movie");const _=document.getElementById("year-dropdown-btn");document.getElementById("year-dropdown-content");document.querySelectorAll(".year-option");let p="",i="";const y={method:"GET",headers:{accept:"application/json",Authorization:`Bearer ${I}`}};document.addEventListener("DOMContentLoaded",()=>{u()});async function u(t=1){try{const n=await(await fetch(`${h}/trending/movie/week?page=${t}`,y)).json();L(n.results),E(n.page,n.total_pages)}catch(e){console.error("Trend filmler yüklenirken hata oluştu:",e),f()}}window.searchMovies=async function(t,e=1,n=""){try{let s;if(t)s=`${h}/search/movie?query=${encodeURIComponent(t)}&page=${e}&include_adult=false`,n&&(s+=`&primary_release_year=${n}`);else if(n)s=`${h}/discover/movie?page=${e}&include_adult=false&sort_by=popularity.desc&primary_release_year=${n}`;else return u(e);const a=await(await fetch(s,y)).json();a.results.length===0?f():(L(a.results),E(a.page,a.total_pages)),p=t,i=n}catch(s){console.error("Film arama sırasında hata oluştu:",s),f()}};function L(t){v.innerHTML="",g.classList.add("hidden"),t.forEach(e=>{const n=e.poster_path?`${B}original${e.poster_path}`:"placeholder-image.jpg",s=document.createElement("div");s.className="movie-card-catalog";const o=e.genre_ids?b(e.genre_ids):[],a=e.release_date?new Date(e.release_date).getFullYear():"";s.innerHTML=`
            <img src="${n}" alt="${e.title}">
            <div class="movie-info-catalog">
                <h3 class="movie-title-catalog">${e.title}</h3>
                <div class="movie-meta">
                    ${o.length?`<span>${o.join(", ")}</span>`:""}
                    ${a?`<span>${a}</span>`:""}
                </div>
                <div class="movie-rating">
                    <div class="stars">★★★★★</div>
                    <span>${e.vote_average.toFixed(1)}</span>
                </div>
            </div>
         
        `,s.addEventListener("click",()=>{w(e)}),v.appendChild(s)})}const $={28:"Aksiyon",12:"Macera",16:"Animasyon",35:"Komedi",80:"Suç",99:"Belgesel",18:"Drama",10751:"Aile",14:"Fantastik",36:"Tarih",27:"Korku",10402:"Müzik",9648:"Gizem",10749:"Romantik",878:"Bilim Kurgu",10770:"TV Film",53:"Gerilim",10752:"Savaş",37:"Vahşi Batı"};function b(t){return t.map(e=>$[e]).filter(e=>e).slice(0,2)}function f(){v.innerHTML="",g.classList.remove("hidden"),l.innerHTML=""}function E(t,e){if(l.innerHTML="",t>1&&r("<",t-1,!1,"prev-btn"),r(1,1,t===1),t>3){const n=document.createElement("span");n.textContent="...",n.className="pagination-ellipsis",l.appendChild(n)}for(let n=Math.max(2,t-1);n<=Math.min(e-1,t+1);n++)r(n,n,t===n);if(t<e-2){const n=document.createElement("span");n.textContent="...",n.className="pagination-ellipsis",l.appendChild(n)}e>1&&r(e,e,t===e),t<e&&r(">",t+1,!1,"next-btn")}function r(t,e,n=!1,s=""){const o=document.createElement("button");o.textContent=t,n&&o.classList.add("active"),s&&o.classList.add(s),o.addEventListener("click",()=>{p?searchMovies(p,e,i):u(e)}),l.appendChild(o)}k.addEventListener("submit",t=>{t.preventDefault();const e=m.value.trim();(e||i)&&(p=e,searchMovies(e,1,i))});m.addEventListener("input",()=>{c&&c.classList.toggle("hidden",!m.value)});c&&c.addEventListener("click",()=>{m.value="",c.classList.add("hidden"),p="",i="",_.innerHTML='Year <span class="dropdown-arrow">▼</span>',u()});document.addEventListener("DOMContentLoaded",()=>{const t=document.getElementById("search-input-catalog"),e=document.getElementById("year-dropdown-btn"),n=document.getElementById("year-dropdown-content"),s=document.querySelector(".year-dropdown-container"),o=document.querySelectorAll(".year-option");t.addEventListener("focus",()=>{t.classList.add("expanded"),s.classList.add("visible")}),e.addEventListener("click",a=>{a.stopPropagation(),n.classList.toggle("show")}),document.addEventListener("click",a=>{const d=a.target.closest("#search-input-catalog")||a.target.closest(".year-dropdown-container")||a.target.closest(".search-button-catalog");!a.target.matches("#year-dropdown-btn")&&!a.target.matches(".dropdown-arrow")&&n.classList.remove("show"),d||t.value.trim()||(t.classList.remove("expanded"),s.classList.remove("visible"))}),t.addEventListener("input",()=>{t.value.trim()&&(t.classList.add("expanded"),s.classList.add("visible"))}),o.forEach(a=>{a.addEventListener("click",()=>{const d=a.getAttribute("data-year");d===""?(i="",e.innerHTML='Year <span class="dropdown-arrow">▼</span>'):(i=d,e.innerHTML=d+' <span class="dropdown-arrow">▼</span>'),o.forEach(M=>M.classList.remove("selected")),a.classList.add("selected"),n.classList.remove("show"),searchMovies(t.value.trim(),1,i)})})});
//# sourceMappingURL=catalog.js.map
