import{o as B}from"./assets/main-CIQFArmN.js";let c=[],o=0;const I=9,g={};document.addEventListener("DOMContentLoaded",()=>{_();const t=document.getElementById("genre-filter");if(t){let n=!1;t.addEventListener("click",()=>{n||(L(),n=!0)}),t.addEventListener("change",r=>{const a=r.target.value;N(a)})}const e=document.getElementById("load-more");e&&e.addEventListener("click",()=>{d(c,!0)}),document.addEventListener("click",n=>{const r=n.target.closest(".movie-card-library");if(r){const a=r.querySelector(".remove-btn").getAttribute("data-id"),l=c.find(i=>i.id==a);if(l)B(l);else return}})});function L(){fetch("https://api.themoviedb.org/3/genre/movie/list?api_key=3c5d79694d82b9e1fe6883553a34fc2d").then(e=>e.json()).then(e=>{const n=e.genres,r=document.getElementById("genre-filter");r.innerHTML="";const a=document.createElement("option");a.value="all",a.textContent="Genre",a.selected=!0,r.appendChild(a),n.forEach(l=>{const i=document.createElement("option");i.value=l.id,i.textContent=l.name,r.appendChild(i),g[l.id]=l.name}),localStorage.setItem("genreMap",JSON.stringify(g)),$()}).catch(e=>{console.error("Error fetching genres:",e)})}function $(){let t=JSON.parse(localStorage.getItem("library"))||[];t=t.map(e=>{if(e.genre_ids&&Array.isArray(e.genre_ids)){const n=e.genre_ids.map(r=>g[r]||"Bilinmeyen").join(", ");return{...e,genre:n}}else if(e.genre&&!isNaN(e.genre))return{...e,genre:g[e.genre]||"Bilinmeyen"};return e}),c=t,o=0,d(t,!1),localStorage.setItem("library",JSON.stringify(t))}const v=document.getElementById("genre-select"),y=document.getElementById("filter-name");function d(t,e=!1){const n=document.getElementById("movie-list-library");if(!n){console.error("'movie-list-library' ID'li element bulunamadı!");return}if(t.length===0){n.innerHTML=`<div class="message-btn-library" >
      <p class ="no-movies-message">OOPS... We are very sorry! You don’t have any movies at your library.</p>
      <button id="go-to-catalog" class="search-btn-library">Search movie</button>
    </div>
  `,y&&(y.style.display="none"),v&&(v.style.display="none");const s=document.getElementById("go-to-catalog");s&&s.addEventListener("click",()=>{window.location.href="catalog.html"});const m=document.getElementById("load-more");m&&(m.style.display="none");return}y&&(y.style.display="block");const r=e?o:0,a=Math.min(r+I,t.length),l=t.slice(r,a);e||(n.innerHTML="");const i=document.createDocumentFragment();l.forEach(s=>{const m=s.poster||`https://image.tmdb.org/t/p/w500${s.poster_path}`,b=s.title,E=s.release_date?s.release_date.slice(0,4):"Yıl yok",h=s.genre||"Kategori belirtilmemiş",p=s.vote_average||0,S=s.id;let f="";p>=8.5?f=`<img src="${base}img/star5.png" alt="5 stars" class="star-icon"/>`:p>=6.5?f=`<img src="${base}img/half4.png" alt="4.5 stars" class="star-icon"/>`:p>=4&&(f=`<img src="${base}img/half3.png" alt="3.5 stars" class="star-icon"/>`);const M=`
      <div class="movie-card-library" data-genre="${h}">
        <img src="${m}" alt="${b}" class="movie-poster-library">
        <div class="movie-info-library">
          <h3 class="movie-title-library">${b} (${E})</h3>
          <div class="movie-rating-library">${f}</div>
          <p class="movie-genre">${h}</p>
        </div>

        <button class="remove-btn" data-id="${S}">Kaldır</button>
      </div>
    `;i.appendChild(document.createRange().createContextualFragment(M))}),o=a,n.appendChild(i);const u=document.getElementById("load-more");u&&(o>=t.length?u.style.display="none":u.style.display="block")}const C=document.querySelectorAll(".remove-btn");C.forEach(t=>{t.addEventListener("click",()=>{const e=t.getAttribute("data-id");O(e)})});function N(t){if(t==="all"){o=0,d(c,!1);return}const e=c.filter(n=>typeof n.genre=="string"?n.genre.includes(g[t])||n.genre===t:Array.isArray(n.genre_ids)?n.genre_ids.includes(Number(t)):!1);o=0,d(e,!1)}function O(t){let e=JSON.parse(localStorage.getItem("library"))||[];e=e.filter(n=>n.id!=t),localStorage.setItem("library",JSON.stringify(e)),c=e,d(e,!1)}function _(){const t=JSON.parse(localStorage.getItem("library"))||[];c=t,o=0,d(t,!1)}
//# sourceMappingURL=myLibrary.js.map
