import{o as I}from"./assets/main-CIQFArmN.js";let c=[],o=0;const L=9,g={};document.addEventListener("DOMContentLoaded",()=>{k();const t=document.getElementById("genre-filter");if(t){let n=!1;t.addEventListener("click",()=>{n||(C(),n=!0)}),t.addEventListener("change",r=>{const a=r.target.value;O(a)})}const e=document.getElementById("load-more");e&&e.addEventListener("click",()=>{d(c,!0)}),document.addEventListener("click",n=>{const r=n.target.closest(".movie-card-library");if(r){const a=r.querySelector(".remove-btn").getAttribute("data-id"),i=c.find(l=>l.id==a);if(i)I(i);else return}})});function C(){fetch("https://api.themoviedb.org/3/genre/movie/list?api_key=3c5d79694d82b9e1fe6883553a34fc2d").then(e=>e.json()).then(e=>{const n=e.genres,r=document.getElementById("genre-filter");r.innerHTML="";const a=document.createElement("option");a.value="all",a.textContent="Genre",a.selected=!0,r.appendChild(a),n.forEach(i=>{const l=document.createElement("option");l.value=i.id,l.textContent=i.name,r.appendChild(l),g[i.id]=i.name}),localStorage.setItem("genreMap",JSON.stringify(g)),$()}).catch(e=>{console.error("Error fetching genres:",e)})}function $(){let t=JSON.parse(localStorage.getItem("library"))||[];t=t.map(e=>{if(e.genre_ids&&Array.isArray(e.genre_ids)){const n=e.genre_ids.map(r=>g[r]||"Bilinmeyen").join(", ");return{...e,genre:n}}else if(e.genre&&!isNaN(e.genre))return{...e,genre:g[e.genre]||"Bilinmeyen"};return e}),c=t,o=0,d(t,!1),localStorage.setItem("library",JSON.stringify(t))}const E=document.getElementById("genre-select"),y=document.getElementById("filter-name");function d(t,e=!1){const n=document.getElementById("movie-list-library");if(!n){console.error("'movie-list-library' ID'li element bulunamadı!");return}if(t.length===0){n.innerHTML=`<div class="message-btn-library" >
      <p class ="no-movies-message">OOPS... We are very sorry! You don’t have any movies at your library.</p>
      <button id="go-to-catalog" class="search-btn-library">Search movie</button>
    </div>
  `,y&&(y.style.display="none"),E&&(E.style.display="none");const s=document.getElementById("go-to-catalog");s&&s.addEventListener("click",()=>{window.location.href="catalog.html"});const m=document.getElementById("load-more");m&&(m.style.display="none");return}y&&(y.style.display="block");const r=e?o:0,a=Math.min(r+L,t.length),i=t.slice(r,a);e||(n.innerHTML="");const l=document.createDocumentFragment();i.forEach(s=>{const m=s.poster||`https://image.tmdb.org/t/p/w500${s.poster_path}`,h=s.title,S=s.release_date?s.release_date.slice(0,4):"Yıl yok",v=s.genre||"Kategori belirtilmemiş",p=s.vote_average||0,M=s.id,b="/Cinemania-JS-Team-D/";let f="";p>=8.5?f=`<img src="${b}img/star5.png" alt="5 stars" class="star-icon"/>`:p>=6.5?f=`<img src="${b}img/half4.png" alt="4.5 stars" class="star-icon"/>`:p>=4&&(f=`<img src="${b}img/half3.png" alt="3.5 stars" class="star-icon"/>`);const B=`
      <div class="movie-card-library" data-genre="${v}">
        <img src="${m}" alt="${h}" class="movie-poster-library">
        <div class="movie-info-library">
          <h3 class="movie-title-library">${h} (${S})</h3>
          <div class="movie-rating-library">${f}</div>
          <p class="movie-genre">${v}</p>
        </div>

        <button class="remove-btn" data-id="${M}">Kaldır</button>
      </div>
    `;l.appendChild(document.createRange().createContextualFragment(B))}),o=a,n.appendChild(l);const u=document.getElementById("load-more");u&&(o>=t.length?u.style.display="none":u.style.display="block")}const N=document.querySelectorAll(".remove-btn");N.forEach(t=>{t.addEventListener("click",()=>{const e=t.getAttribute("data-id");_(e)})});function O(t){if(t==="all"){o=0,d(c,!1);return}const e=c.filter(n=>typeof n.genre=="string"?n.genre.includes(g[t])||n.genre===t:Array.isArray(n.genre_ids)?n.genre_ids.includes(Number(t)):!1);o=0,d(e,!1)}function _(t){let e=JSON.parse(localStorage.getItem("library"))||[];e=e.filter(n=>n.id!=t),localStorage.setItem("library",JSON.stringify(e)),c=e,d(e,!1)}function k(){const t=JSON.parse(localStorage.getItem("library"))||[];c=t,o=0,d(t,!1)}
//# sourceMappingURL=myLibrary.js.map
